//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EShop.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attrib
    {
        public Attrib()
        {
            this.AttributeDescription = new HashSet<AttributeDescription>();
            this.ProductAttributeValue = new HashSet<ProductAttributeValue>();
        }
    
        public long Id { get; set; }
        public int SortOrder { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<System.DateTime> DateModefied { get; set; }
    
        public virtual ICollection<AttributeDescription> AttributeDescription { get; set; }
        public virtual ICollection<ProductAttributeValue> ProductAttributeValue { get; set; }
    }
}
