//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EShop.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttributeDescription
    {
        public long Id { get; set; }
        public long LanguageId { get; set; }
        public long AttributeId { get; set; }
        public string Text { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<System.DateTime> DateModefied { get; set; }
        public Nullable<long> Attrib_Id { get; set; }
    
        public virtual Attrib Attrib { get; set; }
        public virtual Language Language { get; set; }
    }
}
