//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EShop.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Category1 = new HashSet<Category>();
            this.CategoryDescription = new HashSet<CategoryDescription>();
            this.Product = new HashSet<Product>();
        }
    
        public long Id { get; set; }
        public Nullable<long> ParentId { get; set; }
        public string ImageUrl { get; set; }
        public string ImageThumb { get; set; }
        public int SortOrder { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    
        public virtual ICollection<Category> Category1 { get; set; }
        public virtual Category Category2 { get; set; }
        public virtual ICollection<CategoryDescription> CategoryDescription { get; set; }
        public virtual ICollection<Product> Product { get; set; }
    }
}
