//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EShop.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public long Id { get; set; }
        public string ImageUrl { get; set; }
        public string ThumbUrl { get; set; }
        public string AlternateText { get; set; }
        public long ProductId { get; set; }
        public long DesignerId { get; set; }
        public long CategoryId { get; set; }
        public long OptionValueId { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<System.DateTime> DateModefied { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
