//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EShop.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Language
    {
        public Language()
        {
            this.AttributeDescription = new HashSet<AttributeDescription>();
            this.CategoryDescription = new HashSet<CategoryDescription>();
            this.OptionDescription = new HashSet<OptionDescription>();
            this.OptionValueDescription = new HashSet<OptionValueDescription>();
            this.ProductAttributeValue = new HashSet<ProductAttributeValue>();
            this.ProductDescription = new HashSet<ProductDescription>();
            this.TagDescription = new HashSet<TagDescription>();
        }
    
        public long Id { get; set; }
        public string ImageUrl { get; set; }
        public string ImageThumb { get; set; }
        public string Name { get; set; }
        public int Status { get; set; }
        public string Code { get; set; }
        public int SortOrder { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<System.DateTime> DateModefied { get; set; }
    
        public virtual ICollection<AttributeDescription> AttributeDescription { get; set; }
        public virtual ICollection<CategoryDescription> CategoryDescription { get; set; }
        public virtual ICollection<OptionDescription> OptionDescription { get; set; }
        public virtual ICollection<OptionValueDescription> OptionValueDescription { get; set; }
        public virtual ICollection<ProductAttributeValue> ProductAttributeValue { get; set; }
        public virtual ICollection<ProductDescription> ProductDescription { get; set; }
        public virtual ICollection<TagDescription> TagDescription { get; set; }
    }
}
