//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EShop.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Discount = new HashSet<Discount>();
            this.Image = new HashSet<Image>();
            this.Option = new HashSet<Option>();
            this.OptionDescription = new HashSet<OptionDescription>();
            this.OptionValue = new HashSet<OptionValue>();
            this.OptionValueDescription = new HashSet<OptionValueDescription>();
            this.ProductAttributeValue = new HashSet<ProductAttributeValue>();
            this.ProductDescription = new HashSet<ProductDescription>();
            this.ProductRate = new HashSet<ProductRate>();
            this.ProductSKU = new HashSet<ProductSKU>();
            this.ProductSKUOptionValue = new HashSet<ProductSKUOptionValue>();
            this.Tag = new HashSet<Tag>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public double Price { get; set; }
        public long CategoryId { get; set; }
        public long Quantity { get; set; }
        public long DesignerId { get; set; }
        public int SortOrder { get; set; }
        public int Minimum { get; set; }
        public bool Status { get; set; }
        public long NumberOfViews { get; set; }
        public System.DateTime DateAdded { get; set; }
        public System.DateTime DateModefied { get; set; }
        public System.DateTime DateAvailables { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Designer Designer { get; set; }
        public virtual ICollection<Discount> Discount { get; set; }
        public virtual ICollection<Image> Image { get; set; }
        public virtual ICollection<Option> Option { get; set; }
        public virtual ICollection<OptionDescription> OptionDescription { get; set; }
        public virtual ICollection<OptionValue> OptionValue { get; set; }
        public virtual ICollection<OptionValueDescription> OptionValueDescription { get; set; }
        public virtual ICollection<ProductAttributeValue> ProductAttributeValue { get; set; }
        public virtual ICollection<ProductDescription> ProductDescription { get; set; }
        public virtual ICollection<ProductRate> ProductRate { get; set; }
        public virtual ICollection<ProductSKU> ProductSKU { get; set; }
        public virtual ICollection<ProductSKUOptionValue> ProductSKUOptionValue { get; set; }
        public virtual ICollection<Tag> Tag { get; set; }
    }
}
