//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EShop.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        public Tag()
        {
            this.TagDescription = new HashSet<TagDescription>();
            this.Product = new HashSet<Product>();
        }
    
        public long Id { get; set; }
        public System.DateTime DateAdded { get; set; }
        public System.DateTime DateModefied { get; set; }
    
        public virtual ICollection<TagDescription> TagDescription { get; set; }
        public virtual ICollection<Product> Product { get; set; }
    }
}
