// <auto-generated />
namespace EShop.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class drop_order_prop : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(drop_order_prop));
        
        string IMigrationMetadata.Id
        {
            get { return "201612120229151_drop_order_prop"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
