// <auto-generated />
namespace EShop.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class adding_Color_Size_Helpers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adding_Color_Size_Helpers));
        
        string IMigrationMetadata.Id
        {
            get { return "201612181328298_adding_Color_Size_Helpers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
