// <auto-generated />
namespace EShop.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class change_invoiceId_toString : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_invoiceId_toString));
        
        string IMigrationMetadata.Id
        {
            get { return "201612180202496_change_invoiceId_toString"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
