// <auto-generated />
namespace EShop.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class delete_Name_And_ImageURL_From_SizeHelper : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(delete_Name_And_ImageURL_From_SizeHelper));
        
        string IMigrationMetadata.Id
        {
            get { return "201612181755040_delete_Name_And_ImageURL_From_SizeHelper"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
