// <auto-generated />
namespace EShop.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Fixing_Product_Attributes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Fixing_Product_Attributes));
        
        string IMigrationMetadata.Id
        {
            get { return "201701031948408_Fixing_Product_Attributes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
