//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EShop.Resources.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EShopResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EShopResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EShop.Resources.Views.EShopResource", typeof(EShopResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us Short Description.
        /// </summary>
        public static string AboutShort {
            get {
                return ResourceManager.GetString("AboutShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account .
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Information.
        /// </summary>
        public static string AccountInfo {
            get {
                return ResourceManager.GetString("AccountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Cart.
        /// </summary>
        public static string AddToCart {
            get {
                return ResourceManager.GetString("AddToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Compare.
        /// </summary>
        public static string AddToCompare {
            get {
                return ResourceManager.GetString("AddToCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Wishlist.
        /// </summary>
        public static string AddToWishList {
            get {
                return ResourceManager.GetString("AddToWishList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;v read and approved the Terms of Service and Privacy Policy.
        /// </summary>
        public static string AgreeTerms {
            get {
                return ResourceManager.GetString("AgreeTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval for the Terms of Service and Privacy Policy is required.
        /// </summary>
        public static string AgreeTermsRequired {
            get {
                return ResourceManager.GetString("AgreeTermsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Categories.
        /// </summary>
        public static string AllCategories {
            get {
                return ResourceManager.GetString("AllCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Products.
        /// </summary>
        public static string AllProducts {
            get {
                return ResourceManager.GetString("AllProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Rights Reserved.
        /// </summary>
        public static string AllRights {
            get {
                return ResourceManager.GetString("AllRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic.
        /// </summary>
        public static string Arabic {
            get {
                return ResourceManager.GetString("Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availability.
        /// </summary>
        public static string Availability {
            get {
                return ResourceManager.GetString("Availability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Selling.
        /// </summary>
        public static string BestSelling {
            get {
                return ResourceManager.GetString("BestSelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InstaShop.
        /// </summary>
        public static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buyer.
        /// </summary>
        public static string Buyer {
            get {
                return ResourceManager.GetString("Buyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (I want to buy via the website).
        /// </summary>
        public static string BuyerDesc {
            get {
                return ResourceManager.GetString("BuyerDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping Cart.
        /// </summary>
        public static string Cart {
            get {
                return ResourceManager.GetString("Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping Cart is empty.
        /// </summary>
        public static string CartEmpty {
            get {
                return ResourceManager.GetString("CartEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout.
        /// </summary>
        public static string Checkout {
            get {
                return ResourceManager.GetString("Checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Rights Reserved.
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Account.
        /// </summary>
        public static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Account.
        /// </summary>
        public static string CreateNewAccount {
            get {
                return ResourceManager.GetString("CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Service.
        /// </summary>
        public static string CustomerService {
            get {
                return ResourceManager.GetString("CustomerService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomerSupport.
        /// </summary>
        public static string CustomerSupport {
            get {
                return ResourceManager.GetString("CustomerSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Information.
        /// </summary>
        public static string DeliveryInformation {
            get {
                return ResourceManager.GetString("DeliveryInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descriptions.
        /// </summary>
        public static string Descriptions {
            get {
                return ResourceManager.GetString("Descriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        public static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Page.
        /// </summary>
        public static string DisplayPage {
            get {
                return ResourceManager.GetString("DisplayPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US Dollar.
        /// </summary>
        public static string Dollar {
            get {
                return ResourceManager.GetString("Dollar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have account ?.
        /// </summary>
        public static string DontHaveAccount {
            get {
                return ResourceManager.GetString("DontHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email is already used , please choose another one.
        /// </summary>
        public static string EmailExists {
            get {
                return ResourceManager.GetString("EmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail Friend.
        /// </summary>
        public static string EmailFriend {
            get {
                return ResourceManager.GetString("EmailFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your info to login to your account.
        /// </summary>
        public static string EnterLoginInfo {
            get {
                return ResourceManager.GetString("EnterLoginInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQs.
        /// </summary>
        public static string FAQs {
            get {
                return ResourceManager.GetString("FAQs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite.
        /// </summary>
        public static string Favorite {
            get {
                return ResourceManager.GetString("Favorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourite.
        /// </summary>
        public static string Favourite {
            get {
                return ResourceManager.GetString("Favourite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Us.
        /// </summary>
        public static string FollowUs {
            get {
                return ResourceManager.GetString("FollowUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password ?.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        public static string Free {
            get {
                return ResourceManager.GetString("Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get The Latest Deals And Special Offers.
        /// </summary>
        public static string GetTheLatestDealsAndSpecialOffers {
            get {
                return ResourceManager.GetString("GetTheLatestDealsAndSpecialOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid / List.
        /// </summary>
        public static string GridList {
            get {
                return ResourceManager.GetString("GridList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hani.
        /// </summary>
        public static string Hani {
            get {
                return ResourceManager.GetString("Hani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us now.
        /// </summary>
        public static string HeaderDesc {
            get {
                return ResourceManager.GetString("HeaderDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +98 777 666 55.
        /// </summary>
        public static string HeaderSubDesc {
            get {
                return ResourceManager.GetString("HeaderSubDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFORMATION.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email.
        /// </summary>
        public static string InputEmail {
            get {
                return ResourceManager.GetString("InputEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSIDER.
        /// </summary>
        public static string Insider {
            get {
                return ResourceManager.GetString("Insider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instagramkom.
        /// </summary>
        public static string Instagramkom {
            get {
                return ResourceManager.GetString("Instagramkom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InStock.
        /// </summary>
        public static string InStock {
            get {
                return ResourceManager.GetString("InStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email !.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issam.
        /// </summary>
        public static string Issam {
            get {
                return ResourceManager.GetString("Issam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogIn / SignUp.
        /// </summary>
        public static string LogInSignUp {
            get {
                return ResourceManager.GetString("LogInSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login via Email.
        /// </summary>
        public static string LoginViaEmail {
            get {
                return ResourceManager.GetString("LoginViaEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login via Instagram.
        /// </summary>
        public static string LoginViaInstagram {
            get {
                return ResourceManager.GetString("LoginViaInstagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/assets/img/logo.png.
        /// </summary>
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LookBook.
        /// </summary>
        public static string LookBook {
            get {
                return ResourceManager.GetString("LookBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Products.
        /// </summary>
        public static string Mem1 {
            get {
                return ResourceManager.GetString("Mem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create store on instagramkom.
        /// </summary>
        public static string Mem2 {
            get {
                return ResourceManager.GetString("Mem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize store apperance.
        /// </summary>
        public static string Mem3 {
            get {
                return ResourceManager.GetString("Mem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic notification via SMS.
        /// </summary>
        public static string Mem4 {
            get {
                return ResourceManager.GetString("Mem4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special ads on home page.
        /// </summary>
        public static string Mem5 {
            get {
                return ResourceManager.GetString("Mem5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show more from your store.
        /// </summary>
        public static string Mem6 {
            get {
                return ResourceManager.GetString("Mem6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical support 24/7.
        /// </summary>
        public static string Mem7 {
            get {
                return ResourceManager.GetString("Mem7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide services via website .
        /// </summary>
        public static string Mem8 {
            get {
                return ResourceManager.GetString("Mem8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership Subscription.
        /// </summary>
        public static string MembershipSubscription {
            get {
                return ResourceManager.GetString("MembershipSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        public static string Monthly {
            get {
                return ResourceManager.GetString("Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Account.
        /// </summary>
        public static string MyAccount {
            get {
                return ResourceManager.GetString("MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Orders.
        /// </summary>
        public static string MyOrders {
            get {
                return ResourceManager.GetString("MyOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newest First.
        /// </summary>
        public static string NewestFirst {
            get {
                return ResourceManager.GetString("NewestFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEWS.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newsletter.
        /// </summary>
        public static string NewsLetter {
            get {
                return ResourceManager.GetString("NewsLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe at our newsletter.
        /// </summary>
        public static string NewsLetterDesc {
            get {
                return ResourceManager.GetString("NewsLetterDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nodar.
        /// </summary>
        public static string Nodar {
            get {
                return ResourceManager.GetString("Nodar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Of.
        /// </summary>
        public static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and Confirm don&apos;t match.
        /// </summary>
        public static string PassNotEqual {
            get {
                return ResourceManager.GetString("PassNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Methods.
        /// </summary>
        public static string PaymentMethods {
            get {
                return ResourceManager.GetString("PaymentMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} / Page.
        /// </summary>
        public static string PerPage {
            get {
                return ResourceManager.GetString("PerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular Tags.
        /// </summary>
        public static string PopularTags {
            get {
                return ResourceManager.GetString("PopularTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PremiumSeller.
        /// </summary>
        public static string PremiumSeller {
            get {
                return ResourceManager.GetString("PremiumSeller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price : Higher First.
        /// </summary>
        public static string PriceHigh {
            get {
                return ResourceManager.GetString("PriceHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price : Lower First.
        /// </summary>
        public static string PriceLow {
            get {
                return ResourceManager.GetString("PriceLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Price.
        /// </summary>
        public static string ProductPrice {
            get {
                return ResourceManager.GetString("ProductPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUICK OVERVIEW.
        /// </summary>
        public static string QuickOverview {
            get {
                return ResourceManager.GetString("QuickOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate(s).
        /// </summary>
        public static string Rates {
            get {
                return ResourceManager.GetString("Rates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recently Added Items.
        /// </summary>
        public static string RecentlyAddedItems {
            get {
                return ResourceManager.GetString("RecentlyAddedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I want to register as :.
        /// </summary>
        public static string RegisterAs {
            get {
                return ResourceManager.GetString("RegisterAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related Products.
        /// </summary>
        public static string RelatedProducts {
            get {
                return ResourceManager.GetString("RelatedProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me next time ?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field ({0}) required !.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please reset your password by clicking &lt;a href=\&quot;{0}\&quot;&gt;here&lt;/a&gt;.
        /// </summary>
        public static string ResetPasswordBody {
            get {
                return ResourceManager.GetString("ResetPasswordBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Policy.
        /// </summary>
        public static string ReturnPolicy {
            get {
                return ResourceManager.GetString("ReturnPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saudi Rial.
        /// </summary>
        public static string Rial {
            get {
                return ResourceManager.GetString("Rial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale.
        /// </summary>
        public static string Sale {
            get {
                return ResourceManager.GetString("Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAR.
        /// </summary>
        public static string SAR {
            get {
                return ResourceManager.GetString("SAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seller.
        /// </summary>
        public static string Seller {
            get {
                return ResourceManager.GetString("Seller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (I want to build my store via the website).
        /// </summary>
        public static string SellerDesc {
            get {
                return ResourceManager.GetString("SellerDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceProvider.
        /// </summary>
        public static string ServiceProvider {
            get {
                return ResourceManager.GetString("ServiceProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (I want to provide services via website).
        /// </summary>
        public static string ServiceProviderDesc {
            get {
                return ResourceManager.GetString("ServiceProviderDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop By.
        /// </summary>
        public static string ShopBy {
            get {
                return ResourceManager.GetString("ShopBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sitemap.
        /// </summary>
        public static string SiteMap {
            get {
                return ResourceManager.GetString("SiteMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort By.
        /// </summary>
        public static string SortBy {
            get {
                return ResourceManager.GetString("SortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special.
        /// </summary>
        public static string Special {
            get {
                return ResourceManager.GetString("Special", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Offer !.
        /// </summary>
        public static string SpecialOffer {
            get {
                return ResourceManager.GetString("SpecialOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Products.
        /// </summary>
        public static string SpecialProducts {
            get {
                return ResourceManager.GetString("SpecialProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store.
        /// </summary>
        public static string Store {
            get {
                return ResourceManager.GetString("Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input length must be between {0} and {1} characters.
        /// </summary>
        public static string StringLength {
            get {
                return ResourceManager.GetString("StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe.
        /// </summary>
        public static string Subscribe {
            get {
                return ResourceManager.GetString("Subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Year.
        /// </summary>
        public static string SubscriptionPeriod {
            get {
                return ResourceManager.GetString("SubscriptionPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAGs.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms &amp; Conditions.
        /// </summary>
        public static string TermsAndConditions {
            get {
                return ResourceManager.GetString("TermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Service.
        /// </summary>
        public static string TermsOfService {
            get {
                return ResourceManager.GetString("TermsOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instagramkom.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trends.
        /// </summary>
        public static string Trends {
            get {
                return ResourceManager.GetString("Trends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPSELL PRODUCTS.
        /// </summary>
        public static string UpsellProducts {
            get {
                return ResourceManager.GetString("UpsellProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Cart.
        /// </summary>
        public static string ViewCart {
            get {
                return ResourceManager.GetString("ViewCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome To Our Store !.
        /// </summary>
        public static string WelcomeInStore {
            get {
                return ResourceManager.GetString("WelcomeInStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WishList.
        /// </summary>
        public static string WishList {
            get {
                return ResourceManager.GetString("WishList", resourceCulture);
            }
        }
    }
}
